version: '3'
services:
    hugo:
        image: klakegg/hugo:0.93.2-ubuntu
        entrypoint: bash
        volumes:
          - ".:/src"
        ports: 
            - "1313:1313"
        tty: true
        working_dir: /src
